name: Gatsby Publish

on:
  push:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: npm install
      - run: npm run clean
      - run: npm run build
      - uses: actions/checkout@v1
      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: ${{ secrets.BLOG }}
          deploy-branch: master
          gatsby-args: --prefix-paths
