name: Gatsby Publish

on:
  push:
    branches:
      - development
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1      
      - name: yarn install
        run: yarn install
      - name: gatsby build
        run: gatsby build     
      - uses: enriikke/gatsby-gh-pages-action@v2
        with:
          access-token: ${{ secrets.BLOG }}
          deploy-branch: master
          gatsby-args: --prefix-paths
